// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs_hWTL0a_WwC82YfdAmByYAAWzegHrvA',
    appId: '1:257762421649:web:a29675a5b537126e084830',
    messagingSenderId: '257762421649',
    projectId: 'warak-b0c8c',
    authDomain: 'warak-b0c8c.firebaseapp.com',
    storageBucket: 'warak-b0c8c.appspot.com',
    measurementId: 'G-R6S93D8RJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1oBYqUPOB3l3GnHwfEKGELHIW4o70pe4',
    appId: '1:257762421649:android:7ec4e665fdae5cd8084830',
    messagingSenderId: '257762421649',
    projectId: 'warak-b0c8c',
    storageBucket: 'warak-b0c8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEKDvusj2CFbRXbYX_XhmyjKk5dgcB6M',
    appId: '1:257762421649:ios:b9744812f501d49b084830',
    messagingSenderId: '257762421649',
    projectId: 'warak-b0c8c',
    storageBucket: 'warak-b0c8c.appspot.com',
    iosClientId: '257762421649-rfiq0kh9bd3ua4be3orabr81bg3lih63.apps.googleusercontent.com',
    iosBundleId: 'com.example.warak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbEKDvusj2CFbRXbYX_XhmyjKk5dgcB6M',
    appId: '1:257762421649:ios:b9744812f501d49b084830',
    messagingSenderId: '257762421649',
    projectId: 'warak-b0c8c',
    storageBucket: 'warak-b0c8c.appspot.com',
    iosClientId: '257762421649-rfiq0kh9bd3ua4be3orabr81bg3lih63.apps.googleusercontent.com',
    iosBundleId: 'com.example.warak',
  );
}
